package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Adresses generated by hbm2java
 */

public class Adresses implements java.io.Serializable {

	@Override
	public String toString() {
		return "Adresses [idAdresse=" + idAdresse + ", rue=" + rue + ", code="
				+ code + ", ville=" + ville + "]";
	}

	private Integer idAdresse;
	private String rue;
	private String code;
	private String ville;
	private Set userses = new HashSet(0);

	public Adresses() {
	}

	public Adresses(String rue, String code, String ville) {
		this.rue = rue;
		this.code = code;
		this.ville = ville;
	}

	public Adresses(String rue, String code, String ville, Set userses) {
		this.rue = rue;
		this.code = code;
		this.ville = ville;
		this.userses = userses;
	}

	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
