package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Annonces generated by hbm2java
 */
public class Annonces implements java.io.Serializable {

	private Integer idAnnonce;
	private Metiers metiers;
	private Contacts contacts;
	private String secteur;
	private String fonction;
	private String description;
	private Date date;

	public Annonces() {
	}

	public Annonces(Metiers metiers, Contacts contacts, String secteur,
			String fonction, String description, Date date) {
		this.metiers = metiers;
		this.contacts = contacts;
		this.secteur = secteur;
		this.fonction = fonction;
		this.description = description;
		this.date = date;
	}

	public Integer getIdAnnonce() {
		return this.idAnnonce;
	}

	public void setIdAnnonce(Integer idAnnonce) {
		this.idAnnonce = idAnnonce;
	}

	public Metiers getMetiers() {
		return this.metiers;
	}

	public void setMetiers(Metiers metiers) {
		this.metiers = metiers;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public String getSecteur() {
		return this.secteur;
	}

	public void setSecteur(String secteur) {
		this.secteur = secteur;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
