package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Logins generated by hbm2java
 */
public class Logins implements java.io.Serializable {

	@Override
	public String toString() {
		return "Logins [idLogin=" + idLogin + ", roles=" + roles
				+ ", username=" + username + ", password=" + password
				+ ", email=" + email + ", token=" + token + "]";
	}

	private Integer idLogin;
	private Roles roles;
	private String username;
	private String password;
	private String email;
	private String token;
	private Set userses = new HashSet(0);

	public Logins() {
	}

	public Logins(Roles roles, String username, String password, String email) {
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public Logins(Roles roles, String username, String password, String email,
			String token, Set userses) {
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.email = email;
		this.token = token;
		this.userses = userses;
	}

	public Integer getIdLogin() {
		return this.idLogin;
	}

	public void setIdLogin(Integer idLogin) {
		this.idLogin = idLogin;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
