package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.StringEscapeUtils;

/**
 * Metiers generated by hbm2java
 */
public class Metiers implements java.io.Serializable {

	private Integer idMetier;
	private String metier;
	private Set userACommeMetiers = new HashSet(0);
	private Set annonceses = new HashSet(0);

	public Metiers() {
	}

	@Override
	public String toString() {
		return StringEscapeUtils.unescapeHtml4(metier);
	}

	public Metiers(String metier) {
		this.metier = metier;
	}

	public Metiers(String metier, Set userACommeMetiers, Set annonceses) {
		this.metier = metier;
		this.userACommeMetiers = userACommeMetiers;
		this.annonceses = annonceses;
	}

	public Integer getIdMetier() {
		return this.idMetier;
	}

	public void setIdMetier(Integer idMetier) {
		this.idMetier = idMetier;
	}

	public String getMetier() {
		return StringEscapeUtils.unescapeHtml4(this.metier);
	}

	public void setMetier(String metier) {
		this.metier = metier;
	}

	public Set getUserACommeMetiers() {
		return this.userACommeMetiers;
	}

	public void setUserACommeMetiers(Set userACommeMetiers) {
		this.userACommeMetiers = userACommeMetiers;
	}

	public Set getAnnonceses() {
		return this.annonceses;
	}

	public void setAnnonceses(Set annonceses) {
		this.annonceses = annonceses;
	}

}
