package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	@Override
	public String toString() {
		return "Users [idUser=" + idUser + ", nom=" + nom
				+ ", prenom=" + prenom + ", tel=" + tel + ", adresses=" + adresses + ", logins=" + logins
				+ ", rdvses=" + rdvses
				+ ", userACommeMetiers=" + userACommeMetiers + ", users=" + users  + "]";
	}

	private Integer idUser = null;
	private Users users;
	private Logins logins = new Logins();
	private Adresses adresses = new Adresses();
	private String nom;
	private String prenom;
	private String tel;
	private Set rdvses = new HashSet(0);
	private Set userACommeMetiers = new HashSet(0);
	private Set userses = new HashSet(0);

	public Users() {
	}

	public Users(Logins logins, Adresses adresses, String nom, String prenom,
			String tel) {
		this.logins = logins;
		this.adresses = adresses;
		this.nom = nom;
		this.prenom = prenom;
		this.tel = tel;
	}

	public Users(Users users, Logins logins, Adresses adresses, String nom,
			String prenom, String tel, Set rdvses, Set userACommeMetiers,
			Set userses) {
		this.users = users;
		this.logins = logins;
		this.adresses = adresses;
		this.nom = nom;
		this.prenom = prenom;
		this.tel = tel;
		this.rdvses = rdvses;
		this.userACommeMetiers = userACommeMetiers;
		this.userses = userses;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Logins getLogins() {
		return this.logins;
	}

	public void setLogins(Logins logins) {
		this.logins = logins;
	}

	public Adresses getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adresses adresses) {
		this.adresses = adresses;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getRdvses() {
		return this.rdvses;
	}

	public void setRdvses(Set rdvses) {
		this.rdvses = rdvses;
	}

	public Set getUserACommeMetiers() {
		return this.userACommeMetiers;
	}

	public void setUserACommeMetiers(Set userACommeMetiers) {
		this.userACommeMetiers = userACommeMetiers;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Boolean isLogin() {
		if(idUser!=0 && idUser!=null)
		return true;
		else return false;
		
	}
}
