package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

/**
 * UserACommeMetierId generated by hbm2java
 */
public class UserACommeMetierId implements java.io.Serializable {

	private int idUser;
	private int idMetier;

	public UserACommeMetierId() {
	}

	public UserACommeMetierId(int idUser, int idMetier) {
		this.idUser = idUser;
		this.idMetier = idMetier;
	}

	@Override
	public String toString() {
		return "UserACommeMetierId [idUser=" + idUser + ", idMetier="
				+ idMetier + "]";
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdMetier() {
		return this.idMetier;
	}

	public void setIdMetier(int idMetier) {
		this.idMetier = idMetier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserACommeMetierId))
			return false;
		UserACommeMetierId castOther = (UserACommeMetierId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdMetier() == castOther.getIdMetier());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdMetier();
		return result;
	}

}
