package com.interim.model;

import java.util.Date;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

/**
 * Rdvs generated by hbm2java
 */
public class Rdvs implements java.io.Serializable {

	private RdvsId id;
	private Contacts contacts;
	private Users users;
	private Date date;
	private String description;
	private String dir;

	public Rdvs() {
	}

	public Rdvs(RdvsId id, Contacts contacts, Users users, Date date) {
		this.id = id;
		this.contacts = contacts;
		this.users = users;
		this.date = date;
	}

	public Rdvs(RdvsId id, Contacts contacts, Users users, Date date,
			String description, String dir) {
		this.id = id;
		this.contacts = contacts;
		this.users = users;
		this.date = date;
		this.description = description;
		this.dir = dir;
	}

	public RdvsId getId() {
		return this.id;
	}

	public void setId(RdvsId id) {
		this.id = id;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDir() {
		return this.dir;
	}

	public void setDir(String dir) {
		this.dir = dir;
	}

}
