package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer idRole;
	private String role;
	private Set loginses = new HashSet(0);
	

	@Override
	public String toString() {
		return "Roles [idRole=" + idRole + ", role=" + role + "]";
	}

	public Roles() {
	}

	public Roles(String role) {
		this.role = role;
	}

	public Roles(String role, Set loginses) {
		this.role = role;
		this.loginses = loginses;
	}

	public Integer getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getLoginses() {
		return this.loginses;
	}

	public void setLoginses(Set loginses) {
		this.loginses = loginses;
	}

}
